/*Code written by Shangzhen Yang*/
const elements=[{
	"symbol":"H",
	"name":"Hydrogen",
	"name_cn":"氢",
	"mass":1.008
},{
	"symbol":"He",
	"name":"Helium",
	"name_cn":"氦",
	"mass":4.003
},{
	"symbol":"Li",
	"name":"Lithium",
	"name_cn":"锂",
	"mass":6.941
},{
	"symbol":"Be",
	"name":"Beryllium",
	"name_cn":"铍",
	"mass":9.012
},{
	"symbol":"B",
	"name":"Boron",
	"name_cn":"硼",
	"mass":10.811
},{
	"symbol":"C",
	"name":"Carbon",
	"name_cn":"碳",
	"mass":12.011
},{
	"symbol":"N",
	"name":"Nitrogen",
	"name_cn":"氮",
	"mass":14.007
},{
	"symbol":"O",
	"name":"Oxygen",
	"name_cn":"氧",
	"mass":15.999
},{
	"symbol":"F",
	"name":"Fluorine",
	"name_cn":"氟",
	"mass":18.998
},{
	"symbol":"Ne",
	"name":"Neon",
	"name_cn":"氖",
	"mass":20.180
},{
	"symbol":"Na",
	"name":"Sodium",
	"name_cn":"钠",
	"mass":22.990
},{
	"symbol":"Mg",
	"name":"Magnesium",
	"name_cn":"镁",
	"mass":24.305
},{
	"symbol":"Al",
	"name":"Aluminum",
	"name_cn":"铝",
	"mass":26.982
},{
	"symbol":"Si",
	"name":"Silicon",
	"name_cn":"硅",
	"mass":28.086
},{
	"symbol":"P",
	"name":"Phosphorus",
	"name_cn":"磷",
	"mass":30.974
},{
	"symbol":"S",
	"name":"Sulfur",
	"name_cn":"硫",
	"mass":32.066
},{
	"symbol":"Cl",
	"name":"Chlorine",
	"name_cn":"氯",
	"mass":35.453
},{
	"symbol":"Ar",
	"name":"Argon",
	"name_cn":"氩",
	"mass":39.948
},{
	"symbol":"K",
	"name":"Potassium",
	"name_cn":"钾",
	"mass":39.098
},{
	"symbol":"Ca",
	"name":"Calcium",
	"name_cn":"钙",
	"mass":40.078
},{
	"symbol":"Sc",
	"name":"Scandium",
	"name_cn":"钪",
	"mass":44.956
},{
	"symbol":"Ti",
	"name":"Titanium",
	"name_cn":"钛",
	"mass":47.867
},{
	"symbol":"V",
	"name":"Vanadium",
	"name_cn":"钒",
	"mass":50.942
},{
	"symbol":"Cr",
	"name":"Chromium",
	"name_cn":"铬",
	"mass":51.996
},{
	"symbol":"Mn",
	"name":"Manganese",
	"name_cn":"锰",
	"mass":54.938
},{
	"symbol":"Fe",
	"name":"Iron",
	"name_cn":"铁",
	"mass":55.845
},{
	"symbol":"Co",
	"name":"Cobalt",
	"name_cn":"钴",
	"mass":58.933
},{
	"symbol":"Ni",
	"name":"Nickel",
	"name_cn":"镍",
	"mass":58.693
},{
	"symbol":"Cu",
	"name":"Copper",
	"name_cn":"铜",
	"mass":63.546
},{
	"symbol":"Zn",
	"name":"Zinc",
	"name_cn":"锌",
	"mass":65.38
},{
	"symbol":"Ga",
	"name":"Gallium",
	"name_cn":"镓",
	"mass":69.723
},{
	"symbol":"Ge",
	"name":"Germanium",
	"name_cn":"锗",
	"mass":72.630
},{
	"symbol":"As",
	"name":"Arsenic",
	"name_cn":"砷",
	"mass":74.922
},{
	"symbol":"Se",
	"name":"Selenium",
	"name_cn":"硒",
	"mass":78.971
},{
	"symbol":"Br",
	"name":"Bromine",
	"name_cn":"溴",
	"mass":79.904
},{
	"symbol":"Kr",
	"name":"Krypton",
	"name_cn":"氪",
	"mass":83.798
},{
	"symbol":"Rb",
	"name":"Rubidium",
	"name_cn":"铷",
	"mass":85.468
},{
	"symbol":"Sr",
	"name":"Strontium",
	"name_cn":"锶",
	"mass":87.62
},{
	"symbol":"Y",
	"name":"Yttrium",
	"name_cn":"钇",
	"mass":88.906
},{
	"symbol":"Zr",
	"name":"Zirconium",
	"name_cn":"锆",
	"mass":91.224
},{
	"symbol":"Nb",
	"name":"Niobium",
	"name_cn":"铌",
	"mass":92.906
},{
	"symbol":"Mo",
	"name":"Molybdenum",
	"name_cn":"钼",
	"mass":95.95
},{
	"symbol":"Tc",
	"name":"Technetium",
	"name_cn":"锝",
	"mass":98
},{
	"symbol":"Ru",
	"name":"Ruthenium",
	"name_cn":"钌",
	"mass":101.07
},{
	"symbol":"Rh",
	"name":"Rhodium",
	"name_cn":"铑",
	"mass":102.906
},{
	"symbol":"Pd",
	"name":"Palladium",
	"name_cn":"钯",
	"mass":106.42
},{
	"symbol":"Ag",
	"name":"Silver",
	"name_cn":"银",
	"mass":107.868
},{
	"symbol":"Cd",
	"name":"Cadmium",
	"name_cn":"镉",
	"mass":112.411
},{
	"symbol":"In",
	"name":"Indium",
	"name_cn":"铟",
	"mass":114.818
},{
	"symbol":"Sn",
	"name":"Tin",
	"name_cn":"锡",
	"mass":118.710
},{
	"symbol":"Sb",
	"name":"Antimony",
	"name_cn":"锑",
	"mass":121.760
},{
	"symbol":"Te",
	"name":"Tellurium",
	"name_cn":"碲",
	"mass":127.60
},{
	"symbol":"I",
	"name":"Iodine",
	"name_cn":"碘",
	"mass":126.904
},{
	"symbol":"Xe",
	"name":"Xenon",
	"name_cn":"氙",
	"mass":131.29
},{
	"symbol":"Cs",
	"name":"Caesium",
	"name_cn":"铯",
	"mass":132.905
},{
	"symbol":"Ba",
	"name":"Barium",
	"name_cn":"钡",
	"mass":137.327
},{
	"symbol":"La",
	"name":"Lanthanum",
	"name_cn":"镧",
	"mass":138.906
},{
	"symbol":"Ce",
	"name":"Cerium",
	"name_cn":"铈",
	"mass":140.116
},{
	"symbol":"Pr",
	"name":"Praseodymium",
	"name_cn":"镨",
	"mass":140.908
},{
	"symbol":"Nd",
	"name":"Neodymium",
	"name_cn":"钕",
	"mass":144.24
},{
	"symbol":"Pm",
	"name":"Promethium",
	"name_cn":"钷",
	"mass":145
},{
	"symbol":"Sm",
	"name":"Samarium",
	"name_cn":"钐",
	"mass":150.36
},{
	"symbol":"Eu",
	"name":"Europium",
	"name_cn":"铕",
	"mass":151.964
},{
	"symbol":"Gd",
	"name":"Gadolinium",
	"name_cn":"钆",
	"mass":157.25
},{
	"symbol":"Tb",
	"name":"Terbium",
	"name_cn":"铽",
	"mass":158.925
},{
	"symbol":"Dy",
	"name":"Dysprosium",
	"name_cn":"镝",
	"mass":162.50
},{
	"symbol":"Ho",
	"name":"Holmium",
	"name_cn":"钬",
	"mass":164.930
},{
	"symbol":"Er",
	"name":"Erbium",
	"name_cn":"铒",
	"mass":167.26
},{
	"symbol":"Tm",
	"name":"Thulium",
	"name_cn":"铥",
	"mass":168.934
},{
	"symbol":"Yb",
	"name":"Ytterbium",
	"name_cn":"镱",
	"mass":173.05
},{
	"symbol":"Lu",
	"name":"Lutetium",
	"name_cn":"镥",
	"mass":174.967
},{
	"symbol":"Hf",
	"name":"Hafnium",
	"name_cn":"铪",
	"mass":178.49
},{
	"symbol":"Ta",
	"name":"Tantalum",
	"name_cn":"钽",
	"mass":180.948
},{
	"symbol":"W",
	"name":"Tungsten",
	"name_cn":"钨",
	"mass":183.84
},{
	"symbol":"Re",
	"name":"Rhenium",
	"name_cn":"铼",
	"mass":186.207
},{
	"symbol":"Os",
	"name":"Osmium",
	"name_cn":"锇",
	"mass":190.23
},{
	"symbol":"Ir",
	"name":"Iridium",
	"name_cn":"铱",
	"mass":192.217
},{
	"symbol":"Pt",
	"name":"Platinum",
	"name_cn":"铂",
	"mass":195.078
},{
	"symbol":"Au",
	"name":"Gold",
	"name_cn":"金",
	"mass":196.967
},{
	"symbol":"Hg",
	"name":"Mercury",
	"name_cn":"汞",
	"mass":200.59
},{
	"symbol":"Tl",
	"name":"Thallium",
	"name_cn":"铊",
	"mass":204.383
},{
	"symbol":"Pb",
	"name":"Lead",
	"name_cn":"铅",
	"mass":207.2
},{
	"symbol":"Bi",
	"name":"Bismuth",
	"name_cn":"铋",
	"mass":208.980
},{
	"symbol":"Po",
	"name":"Polonium",
	"name_cn":"钋",
	"mass":209
},{
	"symbol":"At",
	"name":"Astatine",
	"name_cn":"砹",
	"mass":210
},{
	"symbol":"Rn",
	"name":"Radon",
	"name_cn":"氡",
	"mass":222
},{
	"symbol":"Fr",
	"name":"Francium",
	"name_cn":"钫",
	"mass":223
},{
	"symbol":"Ra",
	"name":"Radium",
	"name_cn":"镭",
	"mass":226
},{
	"symbol":"Ac",
	"name":"Actinium",
	"name_cn":"锕",
	"mass":227
},{
	"symbol":"Th",
	"name":"Thorium",
	"name_cn":"钍",
	"mass":232.038
},{
	"symbol":"Pa",
	"name":"Protactinium",
	"name_cn":"镤",
	"mass":231.036
},{
	"symbol":"U",
	"name":"Uranium",
	"name_cn":"铀",
	"mass":238.029
},{
	"symbol":"Np",
	"name":"Neptunium",
	"name_cn":"镎",
	"mass":237
},{
	"symbol":"Pu",
	"name":"Plutonium",
	"name_cn":"钚",
	"mass":244
},{
	"symbol":"Am",
	"name":"Americium",
	"name_cn":"镅",
	"mass":243
},{
	"symbol":"Cm",
	"name":"Curium",
	"name_cn":"锔",
	"mass":247
},{
	"symbol":"Bk",
	"name":"Berkelium",
	"name_cn":"锫",
	"mass":247
},{
	"symbol":"Cf",
	"name":"Californium",
	"name_cn":"锎",
	"mass":251
},{
	"symbol":"Es",
	"name":"Einsteinium",
	"name_cn":"锿",
	"mass":252
},{
	"symbol":"Fm",
	"name":"Fermium",
	"name_cn":"镄",
	"mass":257
},{
	"symbol":"Md",
	"name":"Mendelevium",
	"name_cn":"钔",
	"mass":258
},{
	"symbol":"No",
	"name":"Nobelium",
	"name_cn":"锘",
	"mass":259
},{
	"symbol":"Lr",
	"name":"Lawrencium",
	"name_cn":"铹",
	"mass":266
},{
	"symbol":"Rf",
	"name":"Rutherfordium",
	"name_cn":"𬬻",
	"mass":267
},{
	"symbol":"Db",
	"name":"Dubnium",
	"name_cn":"𬭊",
	"mass":268
},{
	"symbol":"Sg",
	"name":"Seaborgium",
	"name_cn":"𬭳",
	"mass":269
},{
	"symbol":"Bh",
	"name":"Bohrium",
	"name_cn":"𬭛",
	"mass":270
},{
	"symbol":"Hs",
	"name":"Hassium",
	"name_cn":"𬭶",
	"mass":277
},{
	"symbol":"Mt",
	"name":"Meitnerium",
	"name_cn":"鿏",
	"mass":278
},{
	"symbol":"Ds",
	"name":"Darmstadtium",
	"name_cn":"𫟼",
	"mass":281
},{
	"symbol":"Rg",
	"name":"Roentgenium",
	"name_cn":"𬬭",
	"mass":282
},{
	"symbol":"Cn",
	"name":"Copernicium",
	"name_cn":"鎶",
	"mass":285
},{
	"symbol":"Nh",
	"name":"Nihonium",
	"name_cn":"鉨",
	"mass":286
},{
	"symbol":"Fl",
	"name":"Flerovium",
	"name_cn":"𫓧",
	"mass":289
},{
	"symbol":"Mc",
	"name":"Moscovium",
	"name_cn":"镆",
	"mass":290
},{
	"symbol":"Lv",
	"name":"Livermorium",
	"name_cn":"鉝",
	"mass":293
},{
	"symbol":"Ts",
	"name":"Tennessine",
	"name_cn":"Tennessine",
	"mass":294
},{
	"symbol":"Og",
	"name":"Oganesson",
	"name_cn":"Oganesson",
	"mass":294
}]
function createList(ul){
	if(ul==null){
		const existingUl=document.getElementsByTagName("ul")
		if(existingUl.length>0){
			ul=existingUl[0]
		}else{
			const newUl=document.createElement("ul")
			document.body.appendChild(newUl)
			ul=newUl
		}
	}
	for(let i=0;i<elements.length;i++){
		const newLi=document.createElement("li")
		newLi.setAttribute("class","periodic-table")
		newLi.id=elements[i].name
		if(navigator.language.indexOf("zh")!=-1){
			newLi.innerText="原子序数："+(i+1)+"\n符号："+elements[i].symbol+"\n名称："+elements[i].name_cn+"\n相对原子质量："+elements[i].mass
		}else{
			newLi.innerText="Atomic number: "+(i+1)+"\nSymbol: "+elements[i].symbol+"\nName: "+elements[i].name+"\nAtomic mass: "+elements[i].mass
		}
		newLi.onclick=function(){
			try{
				elementClicked(getElement(elements[i].name))
			}catch(e){
				console.log(e.message)
			}
		}
		ul.appendChild(newLi)
	}
}
function getElement(searchTerm){
	searchTerm=searchTerm.toLowerCase()
	let mole=1
	for(let i=0;i<elements.length;i++){
		if(searchTerm.substr(0,4)=="mono"){
			mole=1
			searchTerm=searchTerm.replace("mono","")
		}else if(searchTerm.substr(0,2)=="di"){
			mole=2
			searchTerm=searchTerm.replace("di","")
		}else if(searchTerm.substr(0,3)=="tri"){
			mole=3
			searchTerm=searchTerm.replace("tri","")
		}else if(searchTerm.substr(0,5)=="tetra"){
			mole=4
			searchTerm=searchTerm.replace("tetra","")
		}else if(searchTerm.substr(0,5)=="penta"){
			mole=5
			searchTerm=searchTerm.replace("penta","")
		}else if(searchTerm.substr(0,4)=="hexa"){
			mole=6
			searchTerm=searchTerm.replace("hexa","")
		}else if(searchTerm.substr(0,5)=="hepta"){
			mole=7
			searchTerm=searchTerm.replace("hepta","")
		}else if(searchTerm.substr(0,4)=="octa"){
			mole=8
			searchTerm=searchTerm.replace("octa","")
		}else if(searchTerm.substr(0,4)=="nona"){
			mole=9
			searchTerm=searchTerm.replace("nona","")
		}else if(searchTerm.substr(0,4)=="deca"){
			mole=10
			searchTerm=searchTerm.replace("deca","")
		}else if(searchTerm.substr(0,6)=="undeca"){
			mole=11
			searchTerm=searchTerm.replace("undeca","")
		}else if(searchTerm.substr(0,6)=="dodeca"){
			mole=12
			searchTerm=searchTerm.replace("dodeca","")
		}else if(searchTerm.substr(0,1)=="一"){
			mole=1
			searchTerm=searchTerm.replace("一","")
		}else if(searchTerm.substr(0,1)=="二"){
			mole=2
			searchTerm=searchTerm.replace("二","")
		}else if(searchTerm.substr(0,1)=="三"){
			mole=3
			searchTerm=searchTerm.replace("三","")
		}else if(searchTerm.substr(0,1)=="四"){
			mole=4
			searchTerm=searchTerm.replace("四","")
		}else if(searchTerm.substr(0,1)=="五"){
			mole=5
			searchTerm=searchTerm.replace("五","")
		}else if(searchTerm.substr(0,1)=="六"){
			mole=6
			searchTerm=searchTerm.replace("六","")
		}else if(searchTerm.substr(0,1)=="七"){
			mole=7
			searchTerm=searchTerm.replace("七","")
		}else if(searchTerm.substr(0,1)=="八"){
			mole=8
			searchTerm=searchTerm.replace("八","")
		}else if(searchTerm.substr(0,1)=="九"){
			mole=9
			searchTerm=searchTerm.replace("九","")
		}else if(searchTerm.substr(0,1)=="十"){
			mole=10
			searchTerm=searchTerm.replace("十","")
		}
		const isNumber=new RegExp("[0-9]+")
		if(isNumber.test(searchTerm)){
			mole=parseInt(isNumber.exec(searchTerm)[0])
			searchTerm=searchTerm.replace(mole,"")
		}
		if(searchTerm.length<=2&&elements[i].symbol.toLowerCase()==searchTerm||searchTerm.length>2&&elements[i].name.toLowerCase().indexOf(searchTerm)!=-1||elements[i].name_cn==searchTerm||i+1==searchTerm||Math.round(elements[i].mass)==Math.round(searchTerm)){
			return{
				"mass":elements[i].mass*mole,
				"mole":mole,
				"name":elements[i].name,
				"name_cn":elements[i].name_cn,
				"symbol":elements[i].symbol
			}
		}
	}
}
function getCompound(searchTerm){
	searchTerm=searchTerm.trim()
	let mole=1,record=new Array()
	if(searchTerm!=""){
		const isUpperCase=new RegExp("[A-Z]+")
		if(searchTerm.indexOf(" ")!=-1||isUpperCase.test(searchTerm)){
			const letters=searchTerm.split("")
			let tempRecord=new Array()
			searchTerm=""
			for(let i=0;i<letters.length;i++){
				searchTerm+=letters[i]
				const result=getElement(searchTerm.toLowerCase())
				if(result){
					tempRecord.push([{
						"symbol":result.symbol,
						"mole":result.mole,
						"mass":result.mass
					}])
				}
				if(letters[i]==" "||isUpperCase.test(letters[i+1])){
					record.push(tempRecord[tempRecord.length-1])
					tempRecord=new Array()
					mole=1
					searchTerm=""
				}
			}
			record.push(tempRecord[tempRecord.length-1])
		}else if(searchTerm.indexOf("化")!=-1){
			const characters=searchTerm.split("化")
			result=getElement(characters[1])
			record.push([{
				"symbol":result.symbol,
				"mole":result.mole,
				"mass":result.mass
			}])
			mole=1
			result=getElement(characters[0])
			record.push([{
				"symbol":result.symbol,
				"mole":result.mole,
				"mass":result.mass
			}])
		}else{
			return getElement(searchTerm)
		}
		let mass=0,symbol=""
		for(let i=0;i<record.length;i++){
			symbol+=record[i][0].symbol
			if(record[i][0].mole>1){
				symbol+=record[i][0].mole
			}
			mass+=record[i][0].mass
		}
		return{
			"mass":mass,
			"symbol":symbol
		}
	}
}
